/**
 * Backup check-in form (Google Forms).
 *
 * WHAT THIS IS FOR
 * ----------------
 * If the Supabase insert on /attendance fails, the check-in is simply gone —
 * nothing is queued and nothing is retried. During a GBM that means no
 * attendance record for the whole meeting, and the student sees only a generic
 * error. This module builds a link to a Google Form without copying attendee
 * details into the URL. The student enters those details directly on Google's
 * page so names, dot numbers, demographics, and feedback do not land in
 * browser history, proxy logs, referrer headers, screenshots, or copied links.
 *
 * It covers the case where **Supabase is broken but the network is fine** —
 * the project is paused, rate-limited, or a policy got changed. It does NOT
 * help if the venue's wifi is down, because Google is just as unreachable then.
 * That case needs a paper sheet.
 *
 * WHY A LINK AND NOT AN EMBEDDED FORM
 * -----------------------------------
 * vercel.json allows only Cloudflare Turnstile in `frame-src`, so an iframed
 * Google Form is blocked by the Content-Security-Policy. A plain link
 * is not governed by CSP at all (`form-action` restricts where OUR forms post,
 * not where links navigate), so this needs no header change. Do not switch to
 * an embed without adding `frame-src https://docs.google.com` to vercel.json
 * AND verifying it under `npm run preview` — a missing CSP entry is what
 * silently killed the sponsor contact form in production.
 *
 * ── SETUP (see HANDOFF.md "Backup check-in form") ────────────────────────────
 * Until `baseUrl` below is filled in, this is inert: buildFallbackUrl() returns
 * null and the check-in page renders exactly as it does today. Nothing to
 * revert if you decide against it.
 */

/**
 * The Google Form, and which of its fields to prefill.
 *
 * `baseUrl` is the public /viewform URL (from the form's "Send" button → link
 * icon — NOT the /edit URL from the address bar, which a respondent cannot
 * submit).
 *
 * The only supported prefill mapping is `event_name`. An empty string means
 * "do not prefill it" — the form still works and the student selects the event
 * themselves. Do not add attendee fields here: query-string values are stored
 * in browser history and can also appear in logs and copied links.
 *
 * To configure the event mapping safely, first make the Google Form option use
 * the exact canonical `M/D - title` label generated by eventOptionLabel(). Then
 * use Google's "Get pre-filled link" flow to discover that question's
 * `entry.123456789` ID. Never guess an entry ID. The allowlist in
 * buildFallbackUrl() ignores every mapping except `event_name`, even if someone
 * accidentally adds an unsafe mapping to this object later.
 */
export const FALLBACK_FORM = {
  baseUrl:
    'https://docs.google.com/forms/d/e/1FAIpQLSetATIx52meiHRLa0jWvAe67AXKAvlS1D_H3Wy7P2w0v-7wrQ/viewform',
  entries: {
    event_name: '', // unknown: configure only after obtaining the real ID
  },
};

/** True once a form URL has been configured. */
export function isFallbackConfigured(form = FALLBACK_FORM) {
  return typeof form?.baseUrl === 'string' && form.baseUrl.trim() !== '';
}

const GOOGLE_ENTRY_ID = /^entry\.\d+$/;
const CANONICAL_EVENT_LABEL = /^(\d{1,2})\/(\d{1,2}) - .+$/;

function isCanonicalEventLabel(value) {
  if (typeof value !== 'string' || value.length > 500) return false;
  const match = CANONICAL_EVENT_LABEL.exec(value);
  const hasControl = [...value].some((character) => {
    const codePoint = character.codePointAt(0);
    return codePoint <= 31 || codePoint === 127;
  });
  if (!match || hasControl) return false;
  const month = Number(match[1]);
  const day = Number(match[2]);
  return month >= 1 && month <= 12 && day >= 1 && day <= 31;
}

/**
 * Builds the prefilled Google Form URL for a check-in that failed to save.
 * Returns null when no form is configured, which is the signal to render
 * nothing at all rather than a dead button.
 *
 * @param payload the validated attendance fields sent to submit-attendance
 */
export function buildFallbackUrl(payload, form = FALLBACK_FORM) {
  if (!isFallbackConfigured(form) || !payload) return null;

  let url;
  try {
    url = new URL(form.baseUrl.trim());
  } catch {
    return null;
  }

  // A copied "pre-filled link" can already contain entry values. Remove every
  // form answer before adding back the single permitted event value.
  for (const key of [...url.searchParams.keys()]) {
    if (GOOGLE_ENTRY_ID.test(key)) url.searchParams.delete(key);
  }
  url.searchParams.set('usp', 'pp_url');

  // Privacy boundary: only the event label may ever cross into the URL. Do
  // not replace this with an Object.entries(form.entries) loop.
  const eventEntryId = form.entries?.event_name;
  if (GOOGLE_ENTRY_ID.test(eventEntryId ?? '') && isCanonicalEventLabel(payload.event_name)) {
    url.searchParams.set(eventEntryId, payload.event_name);
  }

  return url.toString();
}
