/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-fixed-dim': '#fc6018',
        'on-primary': '#ffefeb',
        'surface-container': '#ede7e2',
        'on-error-container': '#520c00',
        'surface-dim': '#d9d3cd',
        'surface-container-high': '#e7e1dc',
        'inverse-surface': '#0f0e0b',
        'surface-bright': '#fbf5f0',
        'secondary-dim': '#2e4f86',
        'on-tertiary-container': '#523700',
        'tertiary-fixed-dim': '#eda600',
        'inverse-on-surface': '#a09c98',
        'on-primary-fixed-variant': '#531800',
        surface: '#fbf5f0',
        outline: '#7a7672',
        background: '#fbf5f0',
        'on-primary-container': '#441200',
        'error-container': '#f95630',
        'on-surface-variant': '#5e5b57',
        'on-primary-fixed': '#000000',
        'primary-dim': '#8f2f00',
        'surface-tint': '#a33700',
        'secondary-fixed-dim': '#a7c4ff',
        error: '#b02500',
        'tertiary-dim': '#6b4900',
        'on-secondary-fixed': '#0a3368',
        primary: '#a33700',
        'surface-container-highest': '#e2dcd6',
        'primary-container': '#ff7943',
        'secondary-fixed': '#bdd2ff',
        'surface-container-low': '#f6f0ea',
        'error-dim': '#b92902',
        'on-tertiary-fixed-variant': '#5e4000',
        'tertiary-fixed': '#feb300',
        'on-surface': '#302e2b',
        'on-tertiary': '#fff1df',
        'on-background': '#302e2b',
        'secondary-container': '#bdd2ff',
        'surface-variant': '#e2dcd6',
        'tertiary-container': '#feb300',
        secondary: '#3b5b92',
        'surface-container-lowest': '#ffffff',
        'on-secondary-container': '#25477d',
        'primary-fixed': '#ff7943',
        'outline-variant': '#b1aca8',
        'on-tertiary-fixed': '#382400',
        'on-secondary-fixed-variant': '#2f5087',
        'inverse-primary': '#fc6018',
        'on-error': '#ffefec',
        tertiary: '#7b5400',
        'on-secondary': '#eff2ff',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
